keymap("n","gR","<Plug>ReplaceWithRegisterOperator")
keymap("n","gRR","<Plug>ReplaceWithRegisterLine")
keymap("x","gR","<Plug>ReplaceWithRegisterVisual")
delkeymap("n","grr")
delkeymap("n","gr")
delkeymap("x","gr")
